=== phamvanmanh3090-max/TichHopHeThongPhanMem/SanXuatDienThoai_WindowsForms/SanXuatDienThoai.WinForms/SanXuatDienThoai.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
  <xs:simpleType name="NamType">
    <xs:restriction base="xs:integer">
      <xs:minExclusive value="2019"/>
      <xs:maxExclusive value="2024"/>
    </xs:restriction>
  </xs:simpleType>

  <xs:simpleType name="TenCongTyType">
    <xs:restriction base="xs:string">
      <xs:enumeration value="Samsung"/>
      <xs:enumeration value="Apple"/>
      <xs:enumeration value="Xiaomi"/>
    </xs:restriction>
  </xs:simpleType>

  <xs:simpleType name="SoDuongType">
    <xs:restriction base="xs:decimal">
      <xs:minExclusive value="0"/>
    </xs:restriction>
  </xs:simpleType>

  <xs:simpleType name="ThiPhanType">
    <xs:restriction base="xs:decimal">
      <xs:minExclusive value="0"/>
      <xs:maxExclusive value="100"/>
    </xs:restriction>
  </xs:simpleType>

  <xs:element name="sanxuatdienthoai">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="thoigian" minOccurs="1" maxOccurs="2">
          <xs:complexType>
            <xs:sequence>
              <xs:element name="congty" minOccurs="1" maxOccurs="5">
                <xs:complexType>
                  <xs:sequence>
                    <xs:element name="xuatxuong" type="SoDuongType"/>
                    <xs:element name="thiphan" type="ThiPhanType"/>
                  </xs:sequence>
                  <xs:attribute name="ten" type="TenCongTyType" use="required"/>
                </xs:complexType>
              </xs:element>
            </xs:sequence>
            <xs:attribute name="nam" type="NamType" use="required"/>
          </xs:complexType>
        </xs:element>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
</xs:schema>

=== phamvanmanh3090-max/TichHopHeThongPhanMem/SanXuatDienThoai_WindowsForms/SanXuatDienThoai.WinForms/SanXuatDienThoai.xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet type="text/xsl" href="SanXuatDienThoai.xsl"?>
<sanxuatdienthoai xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
                  xsi:noNamespaceSchemaLocation="SanXuatDienThoai.xsd">
  <thoigian nam="2021">
    <congty ten="Samsung">
      <xuatxuong>272.1</xuatxuong>
      <thiphan>20.0</thiphan>
    </congty>
    <congty ten="Apple">
      <xuatxuong>235.8</xuatxuong>
      <thiphan>17.3</thiphan>
    </congty>
    <congty ten="Xiaomi">
      <xuatxuong>191</xuatxuong>
      <thiphan>14</thiphan>
    </congty>
  </thoigian>
  <thoigian nam="2022">
    <congty ten="Samsung">
      <xuatxuong>260.9</xuatxuong>
      <thiphan>21.6</thiphan>
    </congty>
    <congty ten="Apple">
      <xuatxuong>226.4</xuatxuong>
      <thiphan>18.8</thiphan>
    </congty>
    <congty ten="Xiaomi">
      <xuatxuong>153.1</xuatxuong>
      <thiphan>12.7</thiphan>
    </congty>
  </thoigian>
</sanxuatdienthoai>
