=== phamvanmanh3090-max/TichHopHeThongPhanMem/BangGiaXe_WindowsForms/BangGiaXe.WinForms/BangGiaXe.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
  <xs:simpleType name="HangXeType">
    <xs:restriction base="xs:string">
      <xs:enumeration value="Toyota"/>
      <xs:enumeration value="Honda"/>
      <xs:enumeration value="BMW"/>
    </xs:restriction>
  </xs:simpleType>

  <xs:simpleType name="TenDongXeType">
    <xs:restriction base="xs:string">
      <xs:pattern value=".*[0-9]{4}"/>
    </xs:restriction>
  </xs:simpleType>

  <xs:simpleType name="GiaType">
    <xs:restriction base="xs:decimal">
      <xs:minExclusive value="0"/>
    </xs:restriction>
  </xs:simpleType>

  <xs:element name="banggiaxe">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="hangxe" minOccurs="1" maxOccurs="5">
          <xs:complexType>
            <xs:sequence>
              <xs:element name="dongxe" minOccurs="1" maxOccurs="10">
                <xs:complexType>
                  <xs:sequence>
                    <xs:element name="phienban" type="xs:string"/>
                    <xs:element name="dongco" type="xs:string"/>
                    <xs:element name="gia" type="GiaType"/>
                  </xs:sequence>
                  <xs:attribute name="ten" type="TenDongXeType" use="required"/>
                </xs:complexType>
              </xs:element>
            </xs:sequence>
            <xs:attribute name="ten" type="HangXeType" use="required"/>
          </xs:complexType>
        </xs:element>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
</xs:schema>

=== phamvanmanh3090-max/TichHopHeThongPhanMem/BangGiaXe_WindowsForms/BangGiaXe.WinForms/BangGiaXe.xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet type="text/xsl" href="BangGiaXe.xsl"?>
<banggiaxe xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
           xsi:noNamespaceSchemaLocation="BangGiaXe.xsd">
  <hangxe ten="Toyota">
    <dongxe ten="Vios 2021">
      <phienban>E MT</phienban>
      <dongco>2NR-FE</dongco>
      <gia>506</gia>
    </dongxe>
    <dongxe ten="Camry 2022">
      <phienban>2.0G</phienban>
      <dongco>6AR-FSE, 2.0l</dongco>
      <gia>1070</gia>
    </dongxe>
  </hangxe>
  <hangxe ten="Honda">
    <dongxe ten="City 2021">
      <phienban>G</phienban>
      <dongco>1.5 i-VTEC</dongco>
      <gia>529</gia>
    </dongxe>
    <dongxe ten="Accord 2021">
      <phienban>VTEC Turbo</phienban>
      <dongco>1.5 VTEC Turbo</dongco>
      <gia>1319</gia>
    </dongxe>
  </hangxe>
  <hangxe ten="BMW">
    <dongxe ten="X4 2021">
      <phienban>xDrive20i M Sport</phienban>
      <dongco>B48, Xăng I4, 2.0</dongco>
      <gia>3079</gia>
    </dongxe>
    <dongxe ten="Series 3 2021">
      <phienban>320i Sport Line</phienban>
      <dongco>Xăng I4, 2.0</dongco>
      <gia>1899</gia>
    </dongxe>
  </hangxe>
</banggiaxe>
